resources(name="kinect_azure.dae", sources=["kinect_azure.dae"])

resources(name="conveyor_belt.fbx", sources=["conveyor_belt.fbx"])

resources(name="conveyor_belt_extended.fbx", sources=["conveyor_belt_extended.fbx"])
